<?xml version="1.0" encoding="utf-8"?>
<CodeSnippets xmlns="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet">
    <CodeSnippet Format="1.0.0">
        <Header>
            <Title>Pick Elements</Title>
			<Author>Maycon Freitas</Author>
			<Description>Creates a selection of elements in the model.</Description>
			<Shortcut>rvtpickelms</Shortcut>
        </Header>
        <Snippet>
            <Code Language="CSharp">
                <![CDATA[List<Reference> $references$ = $uidoc$.Selection.PickObjects(ObjectType.Element, $selectionFilter$, "$PromptMessage$")?.ToList() ?? new List<Reference>();
                List<Element> $selectedElements$ = $references$.Count > 0 ? $references$.Select(x => $doc$.GetElement(x.ElementId)).ToList() : new List<Element>();]]>
            </Code>
            <Declarations>

                <Literal>
                    <ID>references</ID>
                    <Default>references</Default>
                    <ToolTip>List to receive the references of the selected elements.</ToolTip>
                </Literal>

                <Literal>
                    <ID>uidoc</ID>
                    <Default>commandData.Application.ActiveUIDocument</Default>
                    <ToolTip>The current UIDocument (uidoc).</ToolTip>
                </Literal>

                <Literal>
                    <ID>selectionFilter</ID>
                    <Default>selectionFilter</Default>
                    <ToolTip>The parameter with a instance of the Selection Filter (see snippet rvtselfilt).</ToolTip>
                </Literal>

                <Literal>
                    <ID>PromptMessage</ID>
                    <Default>Select the elements</Default>
                    <ToolTip>Message shown at the prompt.</ToolTip>
                </Literal>

                <Literal>
                    <ID>selectedElements</ID>
                    <Default>selectedElements</Default>
                    <ToolTip>List to receive the elements from references list.</ToolTip>
                </Literal>

                <Literal>
                    <ID>doc</ID>
                    <Default>commandData.Application.ActiveUIDocument.Document</Default>
                    <ToolTip>The current Document (doc).</ToolTip>
                </Literal>

            </Declarations>

            <Imports>
                <Import>
                    <Namespace>Autodesk.Revit.UI.Selection</Namespace>
                </Import>
                <Import>
                    <Namespace>Autodesk.Revit.DB</Namespace>
                </Import>
            </Imports>

        </Snippet>
    </CodeSnippet>
</CodeSnippets>